// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: service.proto

package ai_metathings_component_service_echo

import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/ptypes/wrappers"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *EchoRequest) Validate() error {
	if this.Text != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Text); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Text", err)
		}
	}
	return nil
}
func (this *EchoResponse) Validate() error {
	return nil
}
func (this *StreamingEchoRequest) Validate() error {
	if this.Text != nil {
		if err := github_com_mwitkow_go_proto_validators.CallValidatorIfExists(this.Text); err != nil {
			return github_com_mwitkow_go_proto_validators.FieldError("Text", err)
		}
	}
	return nil
}
func (this *StreamingEchoResponse) Validate() error {
	return nil
}
